### ISSUE TITLE
What's the difference between this and the `msgpack-python`?

### ISSUE THREAD

**Issue by lxyu** [vsergeev/u-msgpack-python#4]
Another repo here: https://github.com/msgpack/msgpack-python

While the official site recommend this `u-msgpack-python`, I'm a little confused.

Both implemented in pure python and both support the latest msgpack 2.0 and both support python2/3.

So what's the difference?

**Comment by stinos** [comment]
Some extra information: there is a performance difference between u-msgpack-python and the pure Python implementation of msgpack-python (the one in it's fallback.py) so if you have to make a choice it might be worth checking if it matters for you.

(I didn't want to make a separate issue for this because it's not really an 'issue', I think, and this turns up in search engines so seems worth adding info here).

For the type of objects we use, something like `{'a': 35, 'b': [1.0, 2.0, 3] * 20, (1): list(range(100)), 'longerKey': 'sab' * 100}` msgpack-python seems to be slightly faster than u-msgpack-python when tested on Windows with CPython 3.7, and somehow twice as fast when tested with MicroPython. However with an object like `list(range(1000))` the winner is u-msgpack-python on CPython (but still about twice as slow on MicroPython).

So if you need a Python implementation and know what objects you're going to use (and they work with both implementations) and performance matters then you probably want to measure first.
