### ISSUE TITLE
Raise exception when default type format is overridden in apllication-defined ext

### ISSUE THREAD

**Issue by giuliano-oliveira** [vsergeev/u-msgpack-python#46]
when having the following code:
```python
import decimal
import struct
import umsgpack

complex_id=0x30
decimal_id=0x40

packed=umsgpack.packb(
    [complex(1,2), decimal.Decimal("0.31")],
    ext_handlers = {
        complex: lambda obj:umsgpack.Ext(complex_id, struct.pack("ff", obj.real, obj.imag)),
        decimal.Decimal: lambda obj:umsgpack.Ext(decimal_id, str(obj).encode()),
    }
)
unpacked=umsgpack.unpackb(
    packed,
    ext_handlers = {
        complex_id: lambda ext: complex(*struct.unpack("ff", ext.data)),
        decimal_id: lambda ext: decimal.Decimal(ext.data.decode()),
})
print(packed.hex(),unpacked)
```
it will output :

> 92d7300000803f00000040d640302e3331 [(1+2j), Decimal('0.31')]

however, if i override the format type of `fixarray` of lenght 2 (bin 1001 0010, hex 92) to the application-defined complex type, by using the same code above, by changing this line:
 ```python
complex_id=0x92
```
i get this output, without an exception

> 92d7920000803f00000040d640302e3331 [<umsgpack.Ext object at 0x7fcc709df470>, Decimal('0.31')]

I think this code should raise an exception, since the programmer can set an already defined type number and confuse the serializer.

**Comment by vsergeev** [comment]
Thanks for the report. The issue is that 0x92 (146) is out of range of a signed 8-bit number (-128 to 127). On the serialize path, it's packed as unsigned 146, but on the deserialize path, it's unpacked as signed -110, which then has no match in the `ext_handlers`, and you get the plain undecoded `Ext` object back.

I will push a fix to validate the range of the type number in both the `Ext` constructor and the `ext_serializable()` decorator.
